# Generated by Django 3.2.3 on 2021-07-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakehouse', '0002_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('Administrador', 'Es administrador'),)},
        ),
    ]
